[install]
state = enabled
build = 1

[ui]
is_visible = true
label = SPL Quiz App

[launcher]
author = Koichi Kuranami
description = SPL Quiz App
version = 0.1.0

[package]
id = spl_quiz
check_for_updates = true
